name: data_class_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.1.2
  source_gen: ^0.9.4+1
  data_class:
    path: ../data_class/

dev_dependencies:
  build_runner: ^1.3.1
